spring:
  config:
    activate:
      on-profile: supabase

  datasource:
    url: jdbc:postgresql://db.brlqmrvnwvtgeqbnsxzj.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate      # ou 'update' si tu veux laisser Hibernate adapter le sch√©ma
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
